### ISSUE TITLE
Back End Part - Business Area - Exception & Transaction Handler

### ISSUE THREAD

**Issue by anasdove** [Polyrific-Inc/Playground#3]
- We should manage how to handle the exception and transaction in business area gracefully.
- This is important for developer especially to handle any specific exception occurred both technical exception or business exception.

Please register the custom filter and create custom exception.

**Comment by ghost** [comment]
I already created new pull request to handle the exception.

**Comment by frandi** [comment]
A global exception handler has been implemented at https://github.com/Polyrific-Inc/Playground/blob/master/PG.Api/Logger/UnhandledExceptionLogger.cs. I think it is enough for now to catch any unhandled exception. More exception handlers for specific business area will be implemented separately as necessary.
