### ISSUE TITLE
IdentityServer4 Implementation

### ISSUE THREAD

**Issue by anasdove** [Polyrific-Inc/Playground#5]
I recommend to implement IdentityServer4 for Membership and Permission purpose.

**Comment by ghost** [comment]
I think the code already used OWIN for membership and permission.

**Comment by ghost** [comment]
apologies, i think I look wrong repo :)

**Comment by frandi** [comment]
Once again, @anasdove suggested the IdentityServer implementation before I put OWIN to this app. It would be very interesting though if he could explain the reasons behind the choice of this stack.

**Comment by frandi** [comment]
I'm closing it for now because we've already had OWIN Identity in-place for the purpose. We might re-open it again in the future if we want to implement `IdentityServer` as the alternative.
