### ISSUE TITLE
Logging Implementation (ELMAH)

### ISSUE THREAD

**Issue by anasdove** [Polyrific-Inc/Playground#6]
I recommend to implement ELMAH for logging the Module and Handler.

**Comment by ghost** [comment]
I think the solution already used NLog as the logger manager, therefore we do not need implement the ELMAH

**Comment by ghost** [comment]
apologies,  i think i look wrong repo :)

**Comment by frandi** [comment]
Actually @anasdove suggested the ELMAH implementation before I put NLog to this app. He might have strong opinion in mentioning ELMAH over other log managers at that time. I think it would be interesting if he wants to jump in now with some argumentation.

**Comment by frandi** [comment]
I'm closing it for now because we've already had `NLog` in place for the logger. We might re-open it again in the future if we want to implement `Elmah` as the alternative.
